port: 4222

tls {
  cert_file: "./certs/server-cert.pem"
  key_file: "./certs/server-key.pem"
}

allow_non_tls: true

authorization {
  timeout: 30
}

jetstream {
  store_dir: "/tmp/nats-jetstream"
}
